[package]
name = "leetcode_rust"
version = "0.1.1"
edition = "2021"
authors = ["Zhongdong Yang <zhongdong_y@outlook.com>"]
categories = ["problems", "algorithm"]
keywords = ["leetcode"]
description = "Personal solutions to LeetCode problems using Rust language"
repository = "https://github.com/zhongdongy/leetcode_rust"

[dependencies]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "leetcode_rust"