name: Deployment

on: [pull_request, push]
jobs:
  build_and_test:
    name: Deploy to Aliyun OSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "mv docs dist"
      - name: Deploy OSS
        uses: JayMeDotDot/aliyun-OSS-deployer@v1.0.0
        with:
          access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          access-key-secret: ${{ secrets.S3_SECRET_KEY }}
          region: ${{ secrets.S3_REGION }}
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: ${{ secrets.S3_ENDPOINT }}