name: Deployment

on: [pull_request, push]
jobs:
  build_and_test:
    name: Deploy to Aliyun OSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./docs/
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
