name: Deployment

on: [pull_request, push]
jobs:
  build_and_test:
    name: Deploy to Aliyun OSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy OSS
        uses: taixw2/deploy-aliyun-oss@v1
        with:
          # aliyun config
          region: ${{ secrets.S3_REGION }} # Full endpoint path from Aliyun Console
          access-key-id: ${{ secrets.S3_ACCESS_KEY }}
          access-key-secret: ${{ secrets.S3_SECRET_KEY }}
          bucket: ${{ secrets.S3_BUCKET }}
          secure: true
          # deploy config
          entry: docs/**/* # glob pattern
          remote-dir: /
          path-rewrite: ^docs/