name: Docs Build & Test

on: [pull_request, push]
jobs:
  build_and_test:
    name: Rust toolchain CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Doctest for all solutions"
        run: "cargo test --doc"