name: 解法验证

on: [pull_request, push]
jobs:
  build_and_test:
    name: Rust toolchain CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        id: "cache-cargo"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: "cargo check"
      - name: "力扣解法的单元测试"
        run: "cargo test --lib problems_cn:: --release"
      - name: "力扣解法的整合测试"
        run: "cargo test --test solutions_cn --release"
