name: Solution Build & Test

on: [pull_request, push]
jobs:
  build_and_test:
    name: Rust toolchain CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Unit test for LeetCode solutions"
        run: "cargo test --lib problems:: --release"
      - name: "Targeted test for LeetCode solutions"
        run: "cargo test --test solutions --release"